// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kujilabo/cocotola-1.23/redstart/user/domain"

	mock "github.com/stretchr/testify/mock"
)

// AuthenticationUsecaseInterface is an autogenerated mock type for the AuthenticationUsecaseInterface type
type AuthenticationUsecaseInterface struct {
	mock.Mock
}

type AuthenticationUsecaseInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthenticationUsecaseInterface) EXPECT() *AuthenticationUsecaseInterface_Expecter {
	return &AuthenticationUsecaseInterface_Expecter{mock: &_m.Mock}
}

// GetUserInfo provides a mock function with given fields: ctx, bearerToken
func (_m *AuthenticationUsecaseInterface) GetUserInfo(ctx context.Context, bearerToken string) (*domain.AppUserModel, error) {
	ret := _m.Called(ctx, bearerToken)

	var r0 *domain.AppUserModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.AppUserModel, error)); ok {
		return rf(ctx, bearerToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.AppUserModel); ok {
		r0 = rf(ctx, bearerToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AppUserModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bearerToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthenticationUsecaseInterface_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type AuthenticationUsecaseInterface_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - bearerToken string
func (_e *AuthenticationUsecaseInterface_Expecter) GetUserInfo(ctx interface{}, bearerToken interface{}) *AuthenticationUsecaseInterface_GetUserInfo_Call {
	return &AuthenticationUsecaseInterface_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, bearerToken)}
}

func (_c *AuthenticationUsecaseInterface_GetUserInfo_Call) Run(run func(ctx context.Context, bearerToken string)) *AuthenticationUsecaseInterface_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthenticationUsecaseInterface_GetUserInfo_Call) Return(_a0 *domain.AppUserModel, _a1 error) *AuthenticationUsecaseInterface_GetUserInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthenticationUsecaseInterface_GetUserInfo_Call) RunAndReturn(run func(context.Context, string) (*domain.AppUserModel, error)) *AuthenticationUsecaseInterface_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *AuthenticationUsecaseInterface) RefreshToken(ctx context.Context, refreshToken string) (string, error) {
	ret := _m.Called(ctx, refreshToken)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthenticationUsecaseInterface_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type AuthenticationUsecaseInterface_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *AuthenticationUsecaseInterface_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *AuthenticationUsecaseInterface_RefreshToken_Call {
	return &AuthenticationUsecaseInterface_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *AuthenticationUsecaseInterface_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *AuthenticationUsecaseInterface_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthenticationUsecaseInterface_RefreshToken_Call) Return(_a0 string, _a1 error) *AuthenticationUsecaseInterface_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthenticationUsecaseInterface_RefreshToken_Call) RunAndReturn(run func(context.Context, string) (string, error)) *AuthenticationUsecaseInterface_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthenticationUsecaseInterface creates a new instance of AuthenticationUsecaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticationUsecaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticationUsecaseInterface {
	mock := &AuthenticationUsecaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
