---
linters-settings:
  gocyclo:
    min-complexity: 15

  staticcheck:
    # https://staticcheck.io/docs/options#checks
    checks: ["all"]

  gocognit:
    min-complexity: 20

  forbidigo:
    forbid:
      - ^fmt\.Print.*$

run:
  go: "1.23"
  build-tags:
    - small
    - medium
    - large
