version: '3'

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  init:
    cmds:
      - go work init
      - go work use -r .

  setup:
    cmds:
      - pre-commit install

  pre-commit:
    cmds:
      - pre-commit run --all-files

  gazelle:
    cmds:
      - bazelisk run //:gazelle 

  mod-tidy:
    cmds:
      - bazelisk run @rules_go//go -- mod tidy

  gen-code-project:
    cmds:
      - |
        pushd {{ .PROJECT }}
        mockery

  gen-code:
    cmds:
      - for:
          - cocotola-auth
          - cocotola-synthesizer
        task: gen-code-project
        vars:
          PROJECT: "{{ .ITEM }}"

  lint-project:
    cmds:
      - |
        pushd {{ .PROJECT }}
        golangci-lint run --config ../.github/golangci.yml --timeout=5m
      # - |
      #   pushd cocotola-synthesizer
      #   pkgforbid -config=../.github/pkgforbid.yml ./...

  lint:
    cmds:
      - for:
          - redstart
          - lib
          - cocotola-synthesizer
          - cocotola-auth
        task: lint-project
        vars:
          PROJECT: "{{ .ITEM }}"

  update-mod-project:
    cmds:
      - |
        pushd {{ .PROJECT }}
        GOPROXY=direct go get -u ./...

  update-mod:
    cmds:
      - for:
          - redstart
          - lib
          - cocotola-synthesizer
          - cocotola-auth
        task: update-mod-project
        vars:
          PROJECT: "{{ .ITEM }}"

  update-repos:
    cmds:
      - bazelisk run //:gazelle-update-repos
  
  run-hello-world:
    cmds:
      - bazelisk run //hello-world:hello-world

  run-third-party-library:
    cmds:
      - bazelisk run //third-party-library:third-party-library

  run-auth:
    cmds:
      - bazelisk run //cocotola-auth:cocotola-auth

  run-synthesizer:
    cmds:
      - bazelisk run //cocotola-synthesizer:cocotola-synthesizer

  build-hello-world:
    cmds:
      - bazelisk run //hello-world:load

  build-project:
    cmds:
      - bazelisk run //{{ .PROJECT }}:load

  build:
    cmds:
      - for:
          - cocotola-synthesizer
          - cocotola-auth
        task: build-project
        vars:
          PROJECT: "{{ .ITEM }}"

  push-project:
    cmds:
      - bazelisk run //{{ .PROJECT }}:push -- --tag {{ .TAG }}

  push:
    cmds:
      - for:
          - cocotola-synthesizer
          # - cocotola-auth
        task: push-project
        vars:
          PROJECT: "{{ .ITEM }}"
          TAG:
            sh: gh release list --json name,isLatest --jq '.[] | select(.isLatest)|.name'

  test:
    cmds:
      - bazelisk test //... --test_output=errors --test_timeout=60 --test_size_filters=small
