version: '3'

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  gazelle:
    cmds:
      - bazelisk run //:gazelle 

  mod-tidy:
    cmds:
      - bazelisk run @rules_go//go -- mod tidy

  update-mod-lib:
    cmds:
      - pushd ./lib/ && GOPROXY=direct go get -u ./... && popd
  
  update-mod-redstart:
    cmds:
      - pushd ./redstart/ && GOPROXY=direct go get -u ./... && popd

  update-mod:
    - task: update-mod-lib
    - task: update-mod-redstart

      # - pushd ./cocotola-synthesizer/ && GOPROXY=direct go get -u ./... && popd

  update-repos:
    cmds:
      - bazelisk run //:gazelle-update-repos
  
  run-hello-world:
    cmds:
      - bazelisk run //hello-world:hello-world

  run-third-party-library:
    cmds:
      - bazelisk run //third-party-library:third-party-library

  run-synthesizer:
    cmds:
      - bazelisk run //cocotola-synthesizer:cocotola-synthesizer


  test:
    cmds:
      - bazelisk test //... --test_output=errors --test_timeout=60 --test_size_filters=small
