---
tatoebaApi:
  endpoint: http://localhost:8280
  username: username
  password: password  # pragma: allowlist secret
datasource:
  tatoeba:
    dir: ${HOME}/pecolynx/cocotola-data/datasource/tatoeba
    engSentences: eng_sentences_detailed_lite.tsv
