---
app:
  authApi:
    endpoint: http://localhost:8080/api/auth
    authType: static
    username: auth_username
    password: auth_password
  ownerLoginId: cocotola-owner
  ownerPassword: password
auth:
  auth:
    signingKey: ah5T9Y9V2JPU74fhCtHQfDqLp3Zg8ZNc
    accessTokenTtlMin: 5
    refreshTokenTtlHour: 720
    googleCallbackUrl: http://localhost:5173/app/auth/callback
    googleClientId: 751610212628-f49u7fr0nivli19pr95eu3ckvn1rcdnn.apps.googleusercontent.com
    googleClientSecret: $GOOGLE_CLIENT_SECRET
    apiTimeoutSec: 5
  ownerLoginId: cocotola-owner
  ownerPassword: password
core:
  authApi:
    endpoint: http://localhost:8080/api/auth
    username: username
    password: password
  synthesizerApi:
    username: username
    password: password
synthesizer:
  internalAuth:
    username: username
    password: password
  googleTextToSpeech:
    apiKey: $GOOGLE_TEXT_TO_SPEECH_API_KEY
    apiTimeoutSec: 5
tatoeba:
  internalAuth:
    username: username
    password: password  # pragma: allowlist secret
server:
  httpPort: 8000
  metricsPort: 8001
  readHeaderTimeoutSec: 30
db:
  driverName: mysql
  migration: true
  mysql:
    username: user
    password: password
    host: 127.0.0.1
    port: 3306
    database: development
  postgres:
    username: user
    password: password
    host: 127.0.0.1
    port: 5432
    database: postgres
trace:
  exporter: otlp
  otlp:
    endpoint: localhost:4318
    insecure: true
cors:
  allowOrigins:
    - '*'
shutdown:
  timeSec1: 1
  timeSec2: 1
log:
  level: debug
swagger:
  enabled: true
  host: localhost:8000
  schema: http
debug:
  gin: true
  wait: false
