---
app:
  authApi:
    endpoint: http://localhost:8080/api/auth
    authType: static
    username: $AUTH_API_USERNAME
    password: $AUTH_API_PASSWORD
  ownerLoginId: $OWNER_LOGIN_ID
  ownerPassword: $OWNER_PASSWORD
auth:
  auth:
    signingKey: $SIGNING_KEY
    accessTokenTtlMin: 30
    refreshTokenTtlHour: 720
    googleProjectId: cocotola-1-23-develop-24-11-02
    googleCallbackUrl: https://www.cocotola.com/app/auth/callback
    googleClientId: 751610212628-2puqbj6bomdj9d6htri9rp4jsi383msn.apps.googleusercontent.com
    googleClientSecret: $GOOGLE_CLIENT_SECRET
  apiTimeoutSec: 5
  ownerLoginId: $OWNER_LOGIN_ID
  ownerPassword: $OWNER_PASSWORD
core:
  authApi:
    endpoint: http://localhost:8080/api/auth
    username: $AUTH_API_USERNAME
    password: $AUTH_API_PASSWORD
  synthesizerApi:
    username: $SYNTHESIZER_API_USERNAME
    password: $SYNTHESIZER_API_PASSWORD
synthesizerApi:
  internalAuth:
    username: $SYNTHESIZER_API_USERNAME
    password: $SYNTHESIZER_API_PASSWORD
  googleTextToSpeech:
    apiKey: $GOOGLE_TEXT_TO_SPEECH_API_KEY
    apiTimeoutSec: 5
tatoeba:
  internalAuth:
    username: $TATOEBA_API_USERNAME
    password: $TATOEBA_API_PASSWORD
server:
  httpPort: 8000
  metricsPort: 8001
  readHeaderTimeoutSec: 30
db:
  driverName: postgres
  migration: false
  postgres:
    username: $POSTGRES_USERNAME
    password: $POSTGRES_PASSWORD
    host: $POSTGRES_HOST
    port: $POSTGRES_PORT
    database: $POSTGRES_DATABASE
trace:
  exporter: none
cors:
  allowOrigins:
    - "https://www.cocotola.com"
shutdown:
  timeSec1: 10
  timeSec2: 10
log:
  level: info
  platform: gcp
swagger:
  enabled: false
  host: localhost:8080
  schema: http
debug:
  gin: false
  wait: false
