---
app:
  internalAuth:
    username: username
    password: password  # pragma: allowlist secret
server:
  httpPort: 8040
  metricsPort: 8041
  readHeaderTimeoutSec: 30
db:
  # driverName: mysql
  # mysql:
  #   username: user
  #   password: password
  #   host: 127.0.0.1
  #   port: 3326
  #   database: development
  driverName: sqlite3
  migration: true
  sqlite3:
    file: tatoeba.db
trace:
  exporter: otlp
  otlp:
    endpoint: localhost:4318
    insecure: true
cors:
  allowOrigins:
    - "*"
shutdown:
  timeSec1: 1
  timeSec2: 1
log:
  level: debug
swagger:
  enabled: true
  host: localhost:8040
  schema: http
debug:
  ginMode: true
  wait: false
