---
app:
  server:
    httpPort: 8080
    metricsPort: 8081
    readHeaderTimeoutSec: 30
  internalAuth:
    username: $AUTH_USERNAME
    password: $AUTH_PASSWORD
db:
  # driverName: sqlite3
  # sqlite3:
  #   file: app.db
  driverName: mysql
  mysql:
    username: $MYSQL_USERNAME
    password: $MYSQL_PASSWORD
    host: $MYSQL_HOST
    port: $MYSQL_PORT
    database: $MYSQL_DATABASE
trace:
  exporter: gcp
cors:
  allowOrigins:
    - https://www.cocotola.com
shutdown:
  timeSec1: 10
  timeSec2: 10
log:
  level: $LOG_LEVEL
swagger:
  enabled: false
  host: cocotola.com
  schema: https
debug:
  ginMode: false
  wait: false
