---
with-expecter: true

mockname: "{{.InterfaceName}}"
outpkg: mocks
filename: "{{.MockName}}.go"
packages:
  github.com/kujilabo/cocotola-1.23/cocotola-auth/controller/gin:
    config:
      dir: controller/gin/mocks
    interfaces:
      AuthenticationUsecase:
      GoogleUserUsecase:
  github.com/kujilabo/cocotola-1.23/cocotola-auth/gateway:
    config:
      dir: gateway/mocks
    interfaces:
      HTTPClient:
issue-845-fix: True
resolve-type-alias: False
