---
with-expecter: true

mockname: "{{.InterfaceName}}"
outpkg: mocks
filename: "{{.MockName}}.go"
packages:
  github.com/kujilabo/cocotola-1.23/cocotola-core/controller/gin:
    config:
      dir: controller/gin/mocks
    interfaces:
      WorkbookQueryUsecase:
      WorkbookCommandUsecase:
  github.com/kujilabo/cocotola-1.23/cocotola-core/service:
    config:
      dir: service/mocks
    interfaces:
      CocotolaAuthClient:
issue-845-fix: True
resolve-type-alias: False
