---
with-expecter: true

mockname: "{{.InterfaceName}}"
outpkg: mocks
filename: "{{.MockName}}.go"
packages:
  github.com/kujilabo/cocotola-1.23/cocotola-synthesizer/controller/gin:
    config:
      dir: controller/gin/mocks
    interfaces:
      SynthesizerUsecase:
issue-845-fix: True
