// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRQeLr6APb1_VDvtRCxzIy2xdhF_DJOAc',
    appId: '1:1038074356214:web:a3fc6a4452dae4cd22e7d7',
    messagingSenderId: '1038074356214',
    projectId: 'cocotola-1-23-develop-24-f88f5',
    authDomain: 'cocotola-1-23-develop-24-f88f5.firebaseapp.com',
    storageBucket: 'cocotola-1-23-develop-24-f88f5.firebasestorage.app',
    measurementId: 'G-7B5SRP4LEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4RGwYglu5BJQkFb-umuVzsfQNwTNetNQ',
    appId: '1:1038074356214:android:dc66252fe75aa6dc22e7d7',
    messagingSenderId: '1038074356214',
    projectId: 'cocotola-1-23-develop-24-f88f5',
    storageBucket: 'cocotola-1-23-develop-24-f88f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBItqU9DT16fuHTdhs6cDYgDfgUfiIlOxc',
    appId: '1:1038074356214:ios:f2388b61bdfa310d22e7d7',
    messagingSenderId: '1038074356214',
    projectId: 'cocotola-1-23-develop-24-f88f5',
    storageBucket: 'cocotola-1-23-develop-24-f88f5.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBItqU9DT16fuHTdhs6cDYgDfgUfiIlOxc',
    appId: '1:1038074356214:ios:f2388b61bdfa310d22e7d7',
    messagingSenderId: '1038074356214',
    projectId: 'cocotola-1-23-develop-24-f88f5',
    storageBucket: 'cocotola-1-23-develop-24-f88f5.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRQeLr6APb1_VDvtRCxzIy2xdhF_DJOAc',
    appId: '1:1038074356214:web:f4cf547393eeab4822e7d7',
    messagingSenderId: '1038074356214',
    projectId: 'cocotola-1-23-develop-24-f88f5',
    authDomain: 'cocotola-1-23-develop-24-f88f5.firebaseapp.com',
    storageBucket: 'cocotola-1-23-develop-24-f88f5.firebasestorage.app',
    measurementId: 'G-GL0QPB9TS4',
  );
}
