// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/kujilabo/cocotola-1.23/cocotola-tatoeba/service"
	mock "github.com/stretchr/testify/mock"
)

// TatoebaLinkAddParameterIterator is an autogenerated mock type for the TatoebaLinkAddParameterIterator type
type TatoebaLinkAddParameterIterator struct {
	mock.Mock
}

type TatoebaLinkAddParameterIterator_Expecter struct {
	mock *mock.Mock
}

func (_m *TatoebaLinkAddParameterIterator) EXPECT() *TatoebaLinkAddParameterIterator_Expecter {
	return &TatoebaLinkAddParameterIterator_Expecter{mock: &_m.Mock}
}

// Next provides a mock function with given fields: ctx
func (_m *TatoebaLinkAddParameterIterator) Next(ctx context.Context) (service.TatoebaLinkAddParameter, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 service.TatoebaLinkAddParameter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (service.TatoebaLinkAddParameter, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) service.TatoebaLinkAddParameter); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.TatoebaLinkAddParameter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TatoebaLinkAddParameterIterator_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type TatoebaLinkAddParameterIterator_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TatoebaLinkAddParameterIterator_Expecter) Next(ctx interface{}) *TatoebaLinkAddParameterIterator_Next_Call {
	return &TatoebaLinkAddParameterIterator_Next_Call{Call: _e.mock.On("Next", ctx)}
}

func (_c *TatoebaLinkAddParameterIterator_Next_Call) Run(run func(ctx context.Context)) *TatoebaLinkAddParameterIterator_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TatoebaLinkAddParameterIterator_Next_Call) Return(_a0 service.TatoebaLinkAddParameter, _a1 error) *TatoebaLinkAddParameterIterator_Next_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TatoebaLinkAddParameterIterator_Next_Call) RunAndReturn(run func(context.Context) (service.TatoebaLinkAddParameter, error)) *TatoebaLinkAddParameterIterator_Next_Call {
	_c.Call.Return(run)
	return _c
}

// NewTatoebaLinkAddParameterIterator creates a new instance of TatoebaLinkAddParameterIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTatoebaLinkAddParameterIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TatoebaLinkAddParameterIterator {
	mock := &TatoebaLinkAddParameterIterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
