// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TatoebaLinkAddParameter is an autogenerated mock type for the TatoebaLinkAddParameter type
type TatoebaLinkAddParameter struct {
	mock.Mock
}

type TatoebaLinkAddParameter_Expecter struct {
	mock *mock.Mock
}

func (_m *TatoebaLinkAddParameter) EXPECT() *TatoebaLinkAddParameter_Expecter {
	return &TatoebaLinkAddParameter_Expecter{mock: &_m.Mock}
}

// GetDst provides a mock function with given fields:
func (_m *TatoebaLinkAddParameter) GetDst() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDst")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// TatoebaLinkAddParameter_GetDst_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDst'
type TatoebaLinkAddParameter_GetDst_Call struct {
	*mock.Call
}

// GetDst is a helper method to define mock.On call
func (_e *TatoebaLinkAddParameter_Expecter) GetDst() *TatoebaLinkAddParameter_GetDst_Call {
	return &TatoebaLinkAddParameter_GetDst_Call{Call: _e.mock.On("GetDst")}
}

func (_c *TatoebaLinkAddParameter_GetDst_Call) Run(run func()) *TatoebaLinkAddParameter_GetDst_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TatoebaLinkAddParameter_GetDst_Call) Return(_a0 int) *TatoebaLinkAddParameter_GetDst_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TatoebaLinkAddParameter_GetDst_Call) RunAndReturn(run func() int) *TatoebaLinkAddParameter_GetDst_Call {
	_c.Call.Return(run)
	return _c
}

// GetSrc provides a mock function with given fields:
func (_m *TatoebaLinkAddParameter) GetSrc() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSrc")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// TatoebaLinkAddParameter_GetSrc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSrc'
type TatoebaLinkAddParameter_GetSrc_Call struct {
	*mock.Call
}

// GetSrc is a helper method to define mock.On call
func (_e *TatoebaLinkAddParameter_Expecter) GetSrc() *TatoebaLinkAddParameter_GetSrc_Call {
	return &TatoebaLinkAddParameter_GetSrc_Call{Call: _e.mock.On("GetSrc")}
}

func (_c *TatoebaLinkAddParameter_GetSrc_Call) Run(run func()) *TatoebaLinkAddParameter_GetSrc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TatoebaLinkAddParameter_GetSrc_Call) Return(_a0 int) *TatoebaLinkAddParameter_GetSrc_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TatoebaLinkAddParameter_GetSrc_Call) RunAndReturn(run func() int) *TatoebaLinkAddParameter_GetSrc_Call {
	_c.Call.Return(run)
	return _c
}

// NewTatoebaLinkAddParameter creates a new instance of TatoebaLinkAddParameter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTatoebaLinkAddParameter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TatoebaLinkAddParameter {
	mock := &TatoebaLinkAddParameter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
