// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/kujilabo/cocotola-1.23/cocotola-tatoeba/service"
	mock "github.com/stretchr/testify/mock"
)

// TatoebaLinkRepository is an autogenerated mock type for the TatoebaLinkRepository type
type TatoebaLinkRepository struct {
	mock.Mock
}

type TatoebaLinkRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TatoebaLinkRepository) EXPECT() *TatoebaLinkRepository_Expecter {
	return &TatoebaLinkRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, param
func (_m *TatoebaLinkRepository) Add(ctx context.Context, param service.TatoebaLinkAddParameter) error {
	ret := _m.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.TatoebaLinkAddParameter) error); ok {
		r0 = rf(ctx, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TatoebaLinkRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type TatoebaLinkRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - param service.TatoebaLinkAddParameter
func (_e *TatoebaLinkRepository_Expecter) Add(ctx interface{}, param interface{}) *TatoebaLinkRepository_Add_Call {
	return &TatoebaLinkRepository_Add_Call{Call: _e.mock.On("Add", ctx, param)}
}

func (_c *TatoebaLinkRepository_Add_Call) Run(run func(ctx context.Context, param service.TatoebaLinkAddParameter)) *TatoebaLinkRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.TatoebaLinkAddParameter))
	})
	return _c
}

func (_c *TatoebaLinkRepository_Add_Call) Return(_a0 error) *TatoebaLinkRepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TatoebaLinkRepository_Add_Call) RunAndReturn(run func(context.Context, service.TatoebaLinkAddParameter) error) *TatoebaLinkRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// NewTatoebaLinkRepository creates a new instance of TatoebaLinkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTatoebaLinkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TatoebaLinkRepository {
	mock := &TatoebaLinkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
