// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/kujilabo/cocotola-1.23/cocotola-tatoeba/service"
	mock "github.com/stretchr/testify/mock"
)

// TatoebaSentenceAddParameterIterator is an autogenerated mock type for the TatoebaSentenceAddParameterIterator type
type TatoebaSentenceAddParameterIterator struct {
	mock.Mock
}

type TatoebaSentenceAddParameterIterator_Expecter struct {
	mock *mock.Mock
}

func (_m *TatoebaSentenceAddParameterIterator) EXPECT() *TatoebaSentenceAddParameterIterator_Expecter {
	return &TatoebaSentenceAddParameterIterator_Expecter{mock: &_m.Mock}
}

// Next provides a mock function with given fields: ctx
func (_m *TatoebaSentenceAddParameterIterator) Next(ctx context.Context) (*service.TatoebaSentenceAddParameter, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 *service.TatoebaSentenceAddParameter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*service.TatoebaSentenceAddParameter, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *service.TatoebaSentenceAddParameter); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.TatoebaSentenceAddParameter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TatoebaSentenceAddParameterIterator_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type TatoebaSentenceAddParameterIterator_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TatoebaSentenceAddParameterIterator_Expecter) Next(ctx interface{}) *TatoebaSentenceAddParameterIterator_Next_Call {
	return &TatoebaSentenceAddParameterIterator_Next_Call{Call: _e.mock.On("Next", ctx)}
}

func (_c *TatoebaSentenceAddParameterIterator_Next_Call) Run(run func(ctx context.Context)) *TatoebaSentenceAddParameterIterator_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TatoebaSentenceAddParameterIterator_Next_Call) Return(_a0 *service.TatoebaSentenceAddParameter, _a1 error) *TatoebaSentenceAddParameterIterator_Next_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TatoebaSentenceAddParameterIterator_Next_Call) RunAndReturn(run func(context.Context) (*service.TatoebaSentenceAddParameter, error)) *TatoebaSentenceAddParameterIterator_Next_Call {
	_c.Call.Return(run)
	return _c
}

// NewTatoebaSentenceAddParameterIterator creates a new instance of TatoebaSentenceAddParameterIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTatoebaSentenceAddParameterIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TatoebaSentenceAddParameterIterator {
	mock := &TatoebaSentenceAddParameterIterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
