---
services:
  dev-cocotola-mysql:
    image: mysql:8.0.40
    container_name: dev-cocotola-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Etc/GMT'
    ports:
      - 3306:3306
  dev-cocotola-postgres:
    image: postgres:15.5-alpine3.19
    container_name: dev-cocotola-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  dev-cocotola-jaeger:
    image: jaegertracing/all-in-one:1.64.0
    container_name: dev-cocotola-jaeger
    ports:
      - 4318:4318
      - 14268:14268
      - 16686:16686
