---
app:
  authApi:
    endpoint: http://localhost:8010
    username: username
    password: password
  synthesizerApi:
    username: username
    password: password
server:
  httpPort: 8020
  metricsPort: 8021
  readHeaderTimeoutSec: 30
db:
  # driverName: sqlite3
  # sqlite3:
  #   file: app.db
  driverName: postgres
  migration: true
  mysql:
    username: user
    password: password
    host: 127.0.0.1
    port: 3326
    database: development
  postgres:
    username: user
    password: password
    host: 127.0.0.1
    port: 5452
    database: postgres
trace:
  exporter: otlp
  otlp:
    endpoint: localhost:4318
    insecure: true
cors:
  allowOrigins:
    - "*"
shutdown:
  timeSec1: 1
  timeSec2: 1
log:
  level: debug
swagger:
  enabled: true
  host: localhost:8020
  schema: http
debug:
  gin: true
  # wait: true
