---
name: Build
on:
  push:
    tags:
      - release/*
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.23.x]
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.REGISTRY_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2

      - run: gcloud info

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: us-east1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - uses: actions/checkout@v4

      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        id: bazel_cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Check cache
        run: ${{ steps.bazel_cache.outputs.cache-hit }}

      - run: bazel info
      
      - uses: arduino/setup-task@v2

      - name: Build
        run: task build

      - run: task push
