---
name: Build
on:
  push:
    tags:
      - "24.*"
      - "25.*"
      - "*"
      - "**"
      - "*.*.*"
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.23.x]
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      # kics-scan ignore-line
      id-token: "write"
    steps:
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.REGISTRY_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2

      - run: ls -la ${GOOGLE_GHA_CREDS_PATH}

      - run: gcloud info
      - uses: actions/checkout@v4

      - run: ls -la ${GOOGLE_GHA_CREDS_PATH}

      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        id: bazel_cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Check cache
        run: ${{ steps.bazel_cache.outputs.cache-hit }}

      - run: bazel info

      - uses: arduino/setup-task@v2

      - run: ls -la ${GOOGLE_GHA_CREDS_PATH}

      - name: Build
        run: task build

      - run: gcloud auth configure-docker us-east1-docker.pkg.dev

      - run: task push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
