---
name: Build
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.23.x]
    runs-on: ubuntu-latest
    permissions:
      # contents: "read"
      # kics-scan ignore-line
      id-token: "write"
    steps:
      - uses: actions/checkout@v4

      # Error: google-github-actions/auth failed with: gitHub Actions did not inject $ACTIONS_ID_TOKEN_REQUEST_TOKEN or $ACTIONS_ID_TOKEN_REQUEST_URL into this job.
      # This most likely means the GitHub Actions workflow permissions are incorrect, or this job is being run from a fork.
      # For more information, please see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.REGISTRY_SERVICE_ACCOUNT_EMAIL }}

        

      - uses: google-github-actions/setup-gcloud@v2

      # - run: ls -la ${GOOGLE_GHA_CREDS_PATH}

      # - run: gcloud info

      # - run: ls -la ${GOOGLE_GHA_CREDS_PATH}

      # - run: echo ${{ github.ref_name}}

      - run: gcloud artifacts repositories describe --location us-east1 cocotola-synthesizer

      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        id: bazel_cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Check cache
        run: echo "cache=${{ steps.bazel_cache.outputs.cache-hit }}"

      - run: bazel info

      - uses: arduino/setup-task@v2

      # - run: ls -la ${GOOGLE_GHA_CREDS_PATH}

      - run: task build

      - run: gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

      - run: TAG=${{ github.ref_name }} task push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
