---
name: Check Flutter
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions: read-all
jobs:
  flutter:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    strategy:
      matrix:
        flutter-version: [3.27.1]
        workdir:
          - cocotola-mobile
    name: flutter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v45
        with:
          files: |
            ${{ matrix.workdir }}/**

      - name: Set up reviewdog
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: reviewdog/action-setup@v1

      - uses: subosito/flutter-action@v2
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        with:
          channel: stable
          flutter-version: ${{ matrix.flutter-version }}

      - run: flutter --version
        if: steps.changed-files-specific.outputs.any_changed == 'true'

      - run: flutter pub get
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        working-directory: ${{ matrix.workdir }}

      - run: flutter analyze | reviewdog -efm="%m ? %f:%l:%c ?%r" -reporter=github-pr-review -tee
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        working-directory: ${{ matrix.workdir }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
