---
name: Create Release
on:
  workflow_dispatch:
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - run: go install github.com/k1LoW/calver/cmd/calver@latest

      - name: Create Release
        run: |
          TAG=gh release list | cut -f 1 | calver --next
          gh release create ${TAG} --generate-notes --target main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
