---
name: PR Test
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.23.x]
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      # kics-scan ignore-line
      id-token: "write"
    steps:
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.REGISTRY_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2

      - run: gcloud info

      - run: gcloud auth configure-docker us-east1-docker.pkg.dev
