---
on: [pull_request]
name: Reviewdog Go
jobs:
  golang:
    strategy:
      matrix:
        workdir:
          - cocotola-auth
          - cocotola-synthesizer
          - lib
          - redstart
    name: golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v45
        with:
          files: |
            ${{ matrix.workdir }}/**

      - name: golangci-lint-default
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: --config=../.github/golangci.yml --timeout=10m
          tool_name: golangci-lint-default
          filter_mode: nofilter
          fail_on_error: true
          workdir: ${{ matrix.workdir }}

      - name: golangci-lint-addition
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: >
            --config=../.github/golangci.yml --disable-all
            -E bodyclose
            -E errorlint
            -E exhaustive
            -E forbidigo
            -E forcetypeassert
            -E gocognit
            -E gocyclo
            -E gofmt
            -E goimports
            -E gosec
            -E noctx
            -E testpackage
            -E thelper
            -E unconvert
            -E whitespace
            --timeout=10m
          tool_name: golangci-lint-addition
          filter_mode: nofilter
          fail_on_error: true
          workdir: ${{ matrix.workdir }}
