---
on: 
  pull_request:
    paths:
      - ".github/**/*.yml"
      - ".github/**/*.yaml"

name: GitHub Actions Lint
jobs:
  actions-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
