---
name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test_go:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3307
          mysql version: "5.7"
          mysql database: "testdb"
          mysql user: "user"
          mysql password: "password"

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v4

      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        id: bazel_cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Check cache
        run: ${{ steps.bazel_cache.outputs.cache-hit }}

      - run: bazel info

      - uses: arduino/setup-task@v2

      - run: task test

      # - name: Coverage
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: coverage.lcov
